
import { FareCategory } from './types';

export const FARE_DATA: FareCategory[] = [
  {
    "category": "Approved Bus Fares 2022 (Paget Farm)",
    "routes": [
      {"name": "Paget Farm to Port Elizabeth", "fare_ec": 2.50},
      {"name": "Paget Farm to Mt. Pleasant", "fare_ec": 2.00},
      {"name": "Paget Farm to Lower Bay Gap", "fare_ec": 2.00},
      {"name": "Paget Farm to Diamond Bus stop", "fare_ec": 2.00},
      {"name": "Port Elizabeth to Barthon Hill", "fare_ec": 2.50},
      {"name": "Port Elizabeth to La Pompe", "fare_ec": 2.00},
      {"name": "Port Elizabeth to Sugar-Apple Inn", "fare_ec": 2.00},
      {"name": "All short drops (less than a mile)", "fare_ec": 2.00}
    ]
  },
  {
    "category": "Approved Bus Fares 2022 (Kingstown to and fro)",
    "routes": [
      {"name": "Chateaubelair", "fare_ec": 8.00},
      {"name": "Fitz Hughes and Beyond", "fare_ec": 8.00},
      {"name": "Rosebank", "fare_ec": 7.00},
      {"name": "Troumaca", "fare_ec": 7.00},
      {"name": "Petit Bordel", "fare_ec": 7.00},
      {"name": "Rose Hall", "fare_ec": 7.00},
      {"name": "Coulls Hill", "fare_ec": 6.00},
      {"name": "Spring Village", "fare_ec": 6.00},
      {"name": "Wallilabou", "fare_ec": 5.00},
      {"name": "Keartons", "fare_ec": 5.00},
      {"name": "Barrouallie", "fare_ec": 5.00},
      {"name": "Layou", "fare_ec": 3.50},
      {"name": "Vermont", "fare_ec": 3.50},
      {"name": "Buccament", "fare_ec": 3.00},
      {"name": "Pembroke", "fare_ec": 3.00},
      {"name": "Rillan", "fare_ec": 2.50},
      {"name": "Clare Valley", "fare_ec": 2.50},
      {"name": "Chauncey", "fare_ec": 2.50},
      {"name": "Questelles", "fare_ec": 2.50},
      {"name": "Campden Park", "fare_ec": 2.50},
      {"name": "Lowmans Hill", "fare_ec": 2.00},
      {"name": "Sion Hill", "fare_ec": 2.00},
      {"name": "Roseau", "fare_ec": 2.00},
      {"name": "Mala Village", "fare_ec": 2.00},
      {"name": "Upper Cane Hall", "fare_ec": 2.50},
      {"name": "Cane Hall/Arnos Vale", "fare_ec": 2.00},
      {"name": "Richland Park", "fare_ec": 5.00},
      {"name": "Carriere", "fare_ec": 3.50},
      {"name": "Riley", "fare_ec": 3.50},
      {"name": "Evesham", "fare_ec": 3.50},
      {"name": "Mesopotamia", "fare_ec": 3.50},
      {"name": "Belmont", "fare_ec": 2.50},
      {"name": "Fairbain Pasture", "fare_ec": 2.50},
      {"name": "Welcome", "fare_ec": 3.00},
      {"name": "Kelbourney", "fare_ec": 3.00},
      {"name": "Gomea", "fare_ec": 2.50},
      {"name": "Belair", "fare_ec": 2.50},
      {"name": "Dauphine", "fare_ec": 2.50},
      {"name": "Fancy", "fare_ec": 9.00},
      {"name": "Owia", "fare_ec": 8.00},
      {"name": "Point", "fare_ec": 8.00},
      {"name": "Sandy Bay", "fare_ec": 8.00},
      {"name": "Overland", "fare_ec": 8.00},
      {"name": "Orange Hill", "fare_ec": 8.00},
      {"name": "Byera", "fare_ec": 6.00},
      {"name": "Colonarie", "fare_ec": 6.00},
      {"name": "South Rivers", "fare_ec": 6.00},
      {"name": "Park Hill", "fare_ec": 6.00},
      {"name": "Georgetown", "fare_ec": 7.00},
      {"name": "Dickson", "fare_ec": 7.00},
      {"name": "Sans Souci", "fare_ec": 6.00},
      {"name": "Diamonds", "fare_ec": 6.00},
      {"name": "New Grounds", "fare_ec": 6.00},
      {"name": "North Union", "fare_ec": 6.00},
      {"name": "Lowmans Wd.", "fare_ec": 6.00},
      {"name": "Greiggs", "fare_ec": 6.00},
      {"name": "Mount Grennan", "fare_ec": 6.00},
      {"name": "South Union", "fare_ec": 6.00},
      {"name": "Cedars", "fare_ec": 5.00},
      {"name": "Bridgetown", "fare_ec": 5.00},
      {"name": "New Prospect", "fare_ec": 5.00},
      {"name": "Peruvian Vale", "fare_ec": 5.00},
      {"name": "Spring Biabou", "fare_ec": 5.00},
      {"name": "Argyle", "fare_ec": 4.00},
      {"name": "Mount Pleasant", "fare_ec": 4.00},
      {"name": "Calder", "fare_ec": 4.00},
      {"name": "Stubbs", "fare_ec": 4.00},
      {"name": "Diamond", "fare_ec": 3.50},
      {"name": "Enhams", "fare_ec": 3.50},
      {"name": "Brighton", "fare_ec": 3.50},
      {"name": "Glamorgan", "fare_ec": 3.50},
      {"name": "Prospect", "fare_ec": 3.00},
      {"name": "Ratho Mill", "fare_ec": 3.00},
      {"name": "Fair Hall", "fare_ec": 3.00},
      {"name": "Calliaqua", "fare_ec": 2.50},
      {"name": "Glen", "fare_ec": 2.50},
      {"name": "Villa", "fare_ec": 2.50},
      {"name": "Fountain", "fare_ec": 2.50},
      {"name": "Sharpes", "fare_ec": 2.00},
      {"name": "Green Hill", "fare_ec": 2.00},
      {"name": "Largo Height", "fare_ec": 2.00},
      {"name": "Edinboro", "fare_ec": 2.00},
      {"name": "Any distance of one mile or less", "fare_ec": 2.00}
    ]
  },
  {
    "category": "Other Bus Routes - Above the Dry River - to and from Georgetown",
    "routes": [
      {"name": "Fancy", "fare_ec": 5.00},
      {"name": "Owia", "fare_ec": 4.00},
      {"name": "Point", "fare_ec": 4.00},
      {"name": "Sandy Bay", "fare_ec": 3.00},
      {"name": "London", "fare_ec": 2.00},
      {"name": "Overland", "fare_ec": 2.00},
      {"name": "Orange Hill", "fare_ec": 2.00},
      {"name": "Magum", "fare_ec": 2.00},
      {"name": "Any distance of one mile or less", "fare_ec": 2.00}
    ]
  },
  {
    "category": "Other Bus Routes - North Leeward - to and from Barrouallie",
    "routes": [
      {"name": "Chateaubelair", "fare_ec": 5.00},
      {"name": "Fitz Hughes and beyond", "fare_ec": 5.00},
      {"name": "Rose Bank", "fare_ec": 4.00},
      {"name": "Troumaca", "fare_ec": 4.00},
      {"name": "Rose Hall", "fare_ec": 4.00},
      {"name": "Petit Bordel", "fare_ec": 4.00},
      {"name": "Coulls Hill", "fare_ec": 3.00},
      {"name": "Spring Village", "fare_ec": 2.50},
      {"name": "Belle Isle", "fare_ec": 2.00},
      {"name": "Any distance of one mile or less", "fare_ec": 2.00}
    ]
  },
  {
    "category": "FROM AIA TO PLACES - TAXI FARES (1 to 3 Passengers)",
    "fares": [
      {"place": "Diamond", "distance_category": "Short Distances", "regular_ec": 39.00, "regular_us": 16.00, "after_hours_ec": 49.00, "after_hours_us": 16.00},
      {"place": "Stubbs", "distance_category": "Short Distances", "regular_ec": 39.00, "regular_us": 16.00, "after_hours_ec": 49.00, "after_hours_us": 16.00},
      {"place": "Carapan", "distance_category": "Short Distances", "regular_ec": 39.00, "regular_us": 16.00, "after_hours_ec": 49.00, "after_hours_us": 16.00},
      {"place": "Enhams", "distance_category": "Short Distances", "regular_ec": 39.00, "regular_us": 16.00, "after_hours_ec": 49.00, "after_hours_us": 16.00},
      {"place": "Mt. Pleasant", "distance_category": "Short Distances", "regular_ec": 39.00, "regular_us": 16.00, "after_hours_ec": 49.00, "after_hours_us": 16.00},
      {"place": "Calder", "distance_category": "Short Distances", "regular_ec": 39.00, "regular_us": 16.00, "after_hours_ec": 49.00, "after_hours_us": 16.00},
      {"place": "La Croix", "distance_category": "Short Distances", "regular_ec": 39.00, "regular_us": 16.00, "after_hours_ec": 49.00, "after_hours_us": 16.00},
      {"place": "Peruvian Vale", "distance_category": "Short Distances", "regular_ec": 39.00, "regular_us": 16.00, "after_hours_ec": 49.00, "after_hours_us": 16.00},
      {"place": "Rawacou", "distance_category": "Short Distances", "regular_ec": 39.00, "regular_us": 16.00, "after_hours_ec": 49.00, "after_hours_us": 16.00},
      {"place": "Biabou", "distance_category": "Short Distances", "regular_ec": 39.00, "regular_us": 16.00, "after_hours_ec": 49.00, "after_hours_us": 16.00},
      {"place": "Cedars", "distance_category": "Short Distances", "regular_ec": 39.00, "regular_us": 16.00, "after_hours_ec": 49.00, "after_hours_us": 16.00},
      {"place": "Spring", "distance_category": "Short Distances", "regular_ec": 39.00, "regular_us": 16.00, "after_hours_ec": 49.00, "after_hours_us": 16.00},
      {"place": "Brighton", "distance_category": "Central Windward Locations", "regular_ec": 52.00, "regular_us": 20.00, "after_hours_ec": 65.00, "after_hours_us": 25.00},
      {"place": "Ratho Mill", "distance_category": "Central Windward Locations", "regular_ec": 65.00, "regular_us": 25.00, "after_hours_ec": 82.00, "after_hours_us": 31.00},
      {"place": "Calliaqua", "distance_category": "Central Windward Locations", "regular_ec": 65.00, "regular_us": 25.00, "after_hours_ec": 82.00, "after_hours_us": 31.00},
      {"place": "Glen", "distance_category": "Central Windward Locations", "regular_ec": 65.00, "regular_us": 25.00, "after_hours_ec": 82.00, "after_hours_us": 31.00},
      {"place": "Fair Hall", "distance_category": "Central Windward Locations", "regular_ec": 72.00, "regular_us": 27.00, "after_hours_ec": 90.00, "after_hours_us": 34.00},
      {"place": "Choppins", "distance_category": "Central Windward Locations", "regular_ec": 72.00, "regular_us": 27.00, "after_hours_ec": 90.00, "after_hours_us": 34.00},
      {"place": "Fountain/Villa", "distance_category": "Central Windward Locations", "regular_ec": 72.00, "regular_us": 27.00, "after_hours_ec": 90.00, "after_hours_us": 34.00},
      {"place": "Arnos Vale", "distance_category": "Central Windward Locations", "regular_ec": 72.00, "regular_us": 27.00, "after_hours_ec": 90.00, "after_hours_us": 34.00},
      {"place": "Cane Hall", "distance_category": "Central Windward Locations", "regular_ec": 78.00, "regular_us": 29.00, "after_hours_ec": 98.00, "after_hours_us": 36.00},
      {"place": "Queens Drive", "distance_category": "Central Windward Locations", "regular_ec": 85.00, "regular_us": 31.00, "after_hours_ec": 107.00, "after_hours_us": 40.00},
      {"place": "Sion Hill Bay", "distance_category": "Central Windward Locations", "regular_ec": 85.00, "regular_us": 31.00, "after_hours_ec": 107.00, "after_hours_us": 40.00},
      {"place": "Frenches", "distance_category": "Central Windward Locations", "regular_ec": 85.00, "regular_us": 31.00, "after_hours_ec": 107.00, "after_hours_us": 40.00},
      {"place": "Cane Garden", "distance_category": "Central Windward Locations", "regular_ec": 91.00, "regular_us": 34.00, "after_hours_ec": 114.00, "after_hours_us": 43.00},
      {"place": "Dorsetshire Hill", "distance_category": "Central Windward Locations", "regular_ec": 91.00, "regular_us": 34.00, "after_hours_ec": 114.00, "after_hours_us": 43.00},
      {"place": "Kingstown", "distance_category": "Central Windward Locations", "regular_ec": 91.00, "regular_us": 34.00, "after_hours_ec": 114.00, "after_hours_us": 43.00},
      {"place": "Murrays Village", "distance_category": "Central Windward Locations", "regular_ec": 91.00, "regular_us": 34.00, "after_hours_ec": 114.00, "after_hours_us": 43.00},
      {"place": "Edinboro", "distance_category": "Central Windward Locations", "regular_ec": 98.00, "regular_us": 36.00, "after_hours_ec": 122.00, "after_hours_us": 47.00},
      {"place": "Old/New Montrose", "distance_category": "Central Windward Locations", "regular_ec": 98.00, "regular_us": 36.00, "after_hours_ec": 122.00, "after_hours_us": 47.00},
      {"place": "Largo Height", "distance_category": "Central Windward Locations", "regular_ec": 98.00, "regular_us": 36.00, "after_hours_ec": 122.00, "after_hours_us": 47.00},
      {"place": "Lodge Village", "distance_category": "Central Windward Locations", "regular_ec": 98.00, "regular_us": 36.00, "after_hours_ec": 122.00, "after_hours_us": 47.00},
      {"place": "Redemption Sharpes", "distance_category": "Central Windward Locations", "regular_ec": 98.00, "regular_us": 36.00, "after_hours_ec": 122.00, "after_hours_us": 47.00},
      {"place": "Green Hill", "distance_category": "Central Windward Locations", "regular_ec": 104.00, "regular_us": 39.00, "after_hours_ec": 130.00, "after_hours_us": 49.00},
      {"place": "Belmont", "distance_category": "Windward/Interior", "regular_ec": 52.00, "regular_us": 20.00, "after_hours_ec": 65.00, "after_hours_us": 25.00},
      {"place": "Evesham", "distance_category": "Windward/Interior", "regular_ec": 52.00, "regular_us": 20.00, "after_hours_ec": 65.00, "after_hours_us": 25.00},
      {"place": "Mesopotamia", "distance_category": "Windward/Interior", "regular_ec": 52.00, "regular_us": 20.00, "after_hours_ec": 65.00, "after_hours_us": 25.00},
      {"place": "Cane End", "distance_category": "Windward/Interior", "regular_ec": 52.00, "regular_us": 20.00, "after_hours_ec": 65.00, "after_hours_us": 25.00},
      {"place": "Richland Park", "distance_category": "Windward/Interior", "regular_ec": 59.00, "regular_us": 22.00, "after_hours_ec": 74.00, "after_hours_us": 27.00},
      {"place": "Dauphine", "distance_category": "Windward/Interior", "regular_ec": 85.00, "regular_us": 31.00, "after_hours_ec": 107.00, "after_hours_us": 40.00},
      {"place": "Gomea (via Highway)", "distance_category": "Windward/Interior", "regular_ec": 85.00, "regular_us": 31.00, "after_hours_ec": 107.00, "after_hours_us": 40.00},
      {"place": "Greiggs", "distance_category": "Windward/Interior", "regular_ec": 78.00, "regular_us": 29.00, "after_hours_ec": 98.00, "after_hours_us": 36.00},
      {"place": "Chapmans", "distance_category": "Windward/Interior", "regular_ec": 78.00, "regular_us": 29.00, "after_hours_ec": 98.00, "after_hours_us": 36.00},
      {"place": "Lowmans Wd.", "distance_category": "Windward/Interior", "regular_ec": 72.00, "regular_us": 27.00, "after_hours_ec": 90.00, "after_hours_us": 34.00},
      {"place": "North & South Union", "distance_category": "Windward/Interior", "regular_ec": 72.00, "regular_us": 27.00, "after_hours_ec": 90.00, "after_hours_us": 34.00},
      {"place": "Mt. Grenan", "distance_category": "Windward/Interior", "regular_ec": 78.00, "regular_us": 29.00, "after_hours_ec": 98.00, "after_hours_us": 46.00},
      {"place": "Colonarie", "distance_category": "Windward/Interior", "regular_ec": 85.00, "regular_us": 31.00, "after_hours_ec": 107.00, "after_hours_us": 40.00},
      {"place": "Park Hill/Byera/Chester", "distance_category": "Windward/Interior", "regular_ec": 91.00, "regular_us": 34.00, "after_hours_ec": 114.00, "after_hours_us": 43.00},
      {"place": "South Rivers", "distance_category": "Windward/Interior", "regular_ec": 98.00, "regular_us": 36.00, "after_hours_ec": 122.00, "after_hours_us": 47.00},
      {"place": "Georgetown", "distance_category": "Windward/Interior", "regular_ec": 104.00, "regular_us": 39.00, "after_hours_ec": 130.00, "after_hours_us": 49.00},
      {"place": "Orange Hill", "distance_category": "Windward/Interior", "regular_ec": 124.00, "regular_us": 47.00, "after_hours_ec": 155.00, "after_hours_us": 59.00},
      {"place": "Overland", "distance_category": "Windward/Interior", "regular_ec": 137.00, "regular_us": 51.00, "after_hours_ec": 172.00, "after_hours_us": 65.00},
      {"place": "Sandy Bay", "distance_category": "Windward/Interior", "regular_ec": 170.00, "regular_us": 64.00, "after_hours_ec": 213.00, "after_hours_us": 81.00},
      {"place": "Owia", "distance_category": "Windward/Interior", "regular_ec": 217.00, "regular_us": 82.00, "after_hours_ec": 272.00, "after_hours_us": 103.00},
      {"place": "Fancy", "distance_category": "Windward/Interior", "regular_ec": 240.00, "regular_us": 90.00, "after_hours_ec": 300.00, "after_hours_us": 113.00},
      {"place": "Lowmans Lwd", "distance_category": "Leeward", "regular_ec": 104.00, "regular_us": 39.00, "after_hours_ec": 130.00, "after_hours_us": 49.00},
      {"place": "Campden Park", "distance_category": "Leeward", "regular_ec": 111.00, "regular_us": 42.00, "after_hours_ec": 139.00, "after_hours_us": 52.00},
      {"place": "Questelles", "distance_category": "Leeward", "regular_ec": 117.00, "regular_us": 44.00, "after_hours_ec": 147.00, "after_hours_us": 56.00},
      {"place": "Chauncey", "distance_category": "Leeward", "regular_ec": 124.00, "regular_us": 47.00, "after_hours_ec": 155.00, "after_hours_us": 59.00},
      {"place": "Clare Valley", "distance_category": "Leeward", "regular_ec": 124.00, "regular_us": 47.00, "after_hours_ec": 155.00, "after_hours_us": 59.00},
      {"place": "Dubois", "distance_category": "Leeward", "regular_ec": 130.00, "regular_us": 48.00, "after_hours_ec": 163.00, "after_hours_us": 61.00},
      {"place": "Pembroke", "distance_category": "Leeward", "regular_ec": 130.00, "regular_us": 48.00, "after_hours_ec": 163.00, "after_hours_us": 61.00},
      {"place": "Vermont", "distance_category": "Leeward", "regular_ec": 130.00, "regular_us": 48.00, "after_hours_ec": 163.00, "after_hours_us": 61.00},
      {"place": "Buccament", "distance_category": "Leeward", "regular_ec": 137.00, "regular_us": 51.00, "after_hours_ec": 172.00, "after_hours_us": 65.00},
      {"place": "Retreat", "distance_category": "Leeward", "regular_ec": 143.00, "regular_us": 53.00, "after_hours_ec": 179.00, "after_hours_us": 68.00},
      {"place": "Layou", "distance_category": "Leeward", "regular_ec": 143.00, "regular_us": 53.00, "after_hours_ec": 179.00, "after_hours_us": 68.00},
      {"place": "Barrouallie", "distance_category": "Leeward", "regular_ec": 169.00, "regular_us": 64.00, "after_hours_ec": 212.00, "after_hours_us": 79.00},
      {"place": "Walliabou", "distance_category": "Leeward", "regular_ec": 176.00, "regular_us": 66.00, "after_hours_ec": 220.00, "after_hours_us": 83.00},
      {"place": "Spring Village", "distance_category": "Leeward", "regular_ec": 202.00, "regular_us": 75.00, "after_hours_ec": 252.00, "after_hours_us": 95.00},
      {"place": "Coulls Hill", "distance_category": "Leeward", "regular_ec": 240.00, "regular_us": 90.00, "after_hours_ec": 302.00, "after_hours_us": 113.00},
      {"place": "Cumberland", "distance_category": "Leeward", "regular_ec": 240.00, "regular_us": 90.00, "after_hours_ec": 302.00, "after_hours_us": 113.00},
      {"place": "Troumaca", "distance_category": "Leeward", "regular_ec": 256.00, "regular_us": 97.00, "after_hours_ec": 321.00, "after_hours_us": 121.00},
      {"place": "Rose Hall", "distance_category": "Leeward", "regular_ec": 272.00, "regular_us": 101.00, "after_hours_ec": 341.00, "after_hours_us": 127.00},
      {"place": "Petite Bordel", "distance_category": "Leeward", "regular_ec": 272.00, "regular_us": 101.00, "after_hours_ec": 341.00, "after_hours_us": 127.00},
      {"place": "Chateaubelair", "distance_category": "Leeward", "regular_ec": 280.00, "regular_us": 105.00, "after_hours_ec": 350.00, "after_hours_us": 131.00},
      {"place": "Richmond", "distance_category": "Leeward", "regular_ec": 295.00, "regular_us": 111.00, "after_hours_ec": 369.00, "after_hours_us": 139.00}
    ]
  },
  {
    "category": "FROM KINGSTOWN TO PLACES - TAXI FARES (Per Passenger)",
    "fares": [
      {"place": "In Kingstown and around", "regular_ec": 13.00, "regular_us": 5.00, "after_hours_ec": 17.00, "after_hours_us": 7.00},
      {"place": "Edinboro", "regular_ec": 20.00, "regular_us": 8.00, "after_hours_ec": 25.00, "after_hours_us": 9.00},
      {"place": "Old/New Montrose", "regular_ec": 20.00, "regular_us": 8.00, "after_hours_ec": 25.00, "after_hours_us": 9.00},
      {"place": "Ottley Hall", "regular_ec": 26.00, "regular_us": 10.00, "after_hours_ec": 33.00, "after_hours_us": 12.00},
      {"place": "Shipyard", "regular_ec": 33.00, "regular_us": 12.00, "after_hours_ec": 40.00, "after_hours_us": 16.00},
      {"place": "Fort Charlotte", "regular_ec": 26.00, "regular_us": 9.00, "after_hours_ec": 33.00, "after_hours_us": 12.00},
      {"place": "Lodge Village", "regular_ec": 20.00, "regular_us": 8.00, "after_hours_ec": 25.00, "after_hours_us": 9.00},
      {"place": "Sharpes (playing field)", "regular_ec": 20.00, "regular_us": 8.00, "after_hours_ec": 25.00, "after_hours_us": 9.00},
      {"place": "Above & Sharpesdale", "regular_ec": 26.00, "regular_us": 9.00, "after_hours_ec": 33.00, "after_hours_us": 12.00},
      {"place": "Green Hill", "regular_ec": 26.00, "regular_us": 9.00, "after_hours_ec": 33.00, "after_hours_us": 12.00},
      {"place": "Green Hill (above junction)", "regular_ec": 33.00, "regular_us": 12.00, "after_hours_ec": 40.00, "after_hours_us": 16.00},
      {"place": "Kingstown Park, Largo Height", "regular_ec": 20.00, "regular_us": 8.00, "after_hours_ec": 25.00, "after_hours_us": 9.00},
      {"place": "Upper (Green Vale)", "regular_ec": 26.00, "regular_us": 9.00, "after_hours_ec": 33.00, "after_hours_us": 12.00},
      {"place": "Murray Village", "regular_ec": 20.00, "regular_us": 8.00, "after_hours_ec": 25.00, "after_hours_us": 9.00},
      {"place": "Upper Murray Village/Rockies", "regular_ec": 26.00, "regular_us": 9.00, "after_hours_ec": 33.00, "after_hours_us": 12.00},
      {"place": "Sion Hill", "regular_ec": 20.00, "regular_us": 8.00, "after_hours_ec": 25.00, "after_hours_us": 9.00},
      {"place": "Upper Sion Hill & Further", "regular_ec": 26.00, "regular_us": 9.00, "after_hours_ec": 33.00, "after_hours_us": 12.00},
      {"place": "Cane Garden", "regular_ec": 20.00, "regular_us": 8.00, "after_hours_ec": 25.00, "after_hours_us": 9.00},
      {"place": "Further Cane Garden-Fly", "regular_ec": 26.00, "regular_us": 9.00, "after_hours_ec": 33.00, "after_hours_us": 12.00},
      {"place": "Walvaroo", "regular_ec": 26.00, "regular_us": 9.00, "after_hours_ec": 33.00, "after_hours_us": 12.00},
      {"place": "Dorsetshire Hill to Miller Gate", "regular_ec": 33.00, "regular_us": 12.00, "after_hours_ec": 40.00, "after_hours_us": 16.00},
      {"place": "Queens Drive", "regular_ec": 39.00, "regular_us": 14.00, "after_hours_ec": 49.00, "after_hours_us": 18.00},
      {"place": "Upper Queens Drive", "regular_ec": 46.00, "regular_us": 17.00, "after_hours_ec": 57.00, "after_hours_us": 21.00},
      {"place": "Arnos Vale", "regular_ec": 33.00, "regular_us": 12.00, "after_hours_ec": 40.00, "after_hours_us": 16.00},
      {"place": "Fountain", "regular_ec": 33.00, "regular_us": 12.00, "after_hours_ec": 40.00, "after_hours_us": 16.00},
      {"place": "Villa", "regular_ec": 39.00, "regular_us": 14.00, "after_hours_ec": 49.00, "after_hours_us": 18.00},
      {"place": "Calliaqua", "regular_ec": 39.00, "regular_us": 14.00, "after_hours_ec": 49.00, "after_hours_us": 18.00},
      {"place": "Fair Hall", "regular_ec": 52.00, "regular_us": 20.00, "after_hours_ec": 65.00, "after_hours_us": 25.00},
      {"place": "Belair", "distance_category": "To Interior", "regular_ec": 39.00, "regular_us": 14.00, "after_hours_ec": 49.00, "after_hours_us": 18.00},
      {"place": "Gomea (to Catholic Church)", "distance_category": "To Interior", "regular_ec": 46.00, "regular_us": 17.00, "after_hours_ec": 57.00, "after_hours_us": 21.00},
      {"place": "Kelborney", "distance_category": "To Interior", "regular_ec": 59.00, "regular_us": 22.00, "after_hours_ec": 73.00, "after_hours_us": 27.00},
      {"place": "Evesham", "distance_category": "To Interior", "regular_ec": 65.00, "regular_us": 25.00, "after_hours_ec": 82.00, "after_hours_us": 30.00},
      {"place": "Fairbain Pasture", "distance_category": "To Interior", "regular_ec": 39.00, "regular_us": 14.00, "after_hours_ec": 49.00, "after_hours_us": 18.00},
      {"place": "Belmont", "distance_category": "To Interior", "regular_ec": 46.00, "regular_us": 17.00, "after_hours_ec": 57.00, "after_hours_us": 21.00},
      {"place": "La Croix", "distance_category": "To Interior", "regular_ec": 52.00, "regular_us": 20.00, "after_hours_ec": 65.00, "after_hours_us": 25.00},
      {"place": "Mesopotamia (to Police Station)", "distance_category": "To Interior", "regular_ec": 65.00, "regular_us": 25.00, "after_hours_ec": 82.00, "after_hours_us": 30.00},
      {"place": "Cane End", "distance_category": "To Interior", "regular_ec": 78.00, "regular_us": 29.00, "after_hours_ec": 98.00, "after_hours_us": 36.00},
      {"place": "Yambou", "distance_category": "To Interior", "regular_ec": 78.00, "regular_us": 29.00, "after_hours_ec": 98.00, "after_hours_us": 36.00},
      {"place": "Richland Park", "distance_category": "To Interior", "regular_ec": 78.00, "regular_us": 29.00, "after_hours_ec": 98.00, "after_hours_us": 36.00},
      {"place": "Maroon Hill", "distance_category": "To Interior", "regular_ec": 91.00, "regular_us": 34.00, "after_hours_ec": 114.00, "after_hours_us": 23.00},
      {"place": "Chapmans", "distance_category": "To Interior", "regular_ec": 117.00, "regular_us": 44.00, "after_hours_ec": 147.00, "after_hours_us": 55.00},
      {"place": "Ratho Mill", "distance_category": "To Windward", "regular_ec": 46.00, "regular_us": 17.00, "after_hours_ec": 57.00, "after_hours_us": 21.00},
      {"place": "Prospect to Belvedere Gap", "distance_category": "To Windward", "regular_ec": 52.00, "regular_us": 20.00, "after_hours_ec": 65.00, "after_hours_us": 25.00},
      {"place": "Brighton", "distance_category": "To Windward", "regular_ec": 59.00, "regular_us": 22.00, "after_hours_ec": 73.00, "after_hours_us": 27.00},
      {"place": "Diamond", "distance_category": "To Windward", "regular_ec": 59.00, "regular_us": 22.00, "after_hours_ec": 73.00, "after_hours_us": 27.00},
      {"place": "Stubbs", "distance_category": "To Windward", "regular_ec": 65.00, "regular_us": 25.00, "after_hours_ec": 82.00, "after_hours_us": 30.00},
      {"place": "Calder", "distance_category": "To Windward", "regular_ec": 65.00, "regular_us": 25.00, "after_hours_ec": 82.00, "after_hours_us": 30.00},
      {"place": "Argyle", "distance_category": "To Windward", "regular_ec": 91.00, "regular_us": 34.00, "after_hours_ec": 114.00, "after_hours_us": 43.00},
      {"place": "Peruvian Vale", "distance_category": "To Windward", "regular_ec": 91.00, "regular_us": 34.00, "after_hours_ec": 114.00, "after_hours_us": 43.00},
      {"place": "Spring", "distance_category": "To Windward", "regular_ec": 104.00, "regular_us": 39.00, "after_hours_ec": 130.00, "after_hours_us": 48.00},
      {"place": "Biabou", "distance_category": "To Windward", "regular_ec": 111.00, "regular_us": 42.00, "after_hours_ec": 138.00, "after_hours_us": 52.00},
      {"place": "Cedars", "distance_category": "To Windward", "regular_ec": 111.00, "regular_us": 42.00, "after_hours_ec": 138.00, "after_hours_us": 52.00},
      {"place": "South Union", "distance_category": "To Windward", "regular_ec": 117.00, "regular_us": 44.00, "after_hours_ec": 147.00, "after_hours_us": 55.00},
      {"place": "Diamonds Gap & Up", "distance_category": "To Windward", "regular_ec": 124.00, "regular_us": 47.00, "after_hours_ec": 155.00, "after_hours_us": 57.00},
      {"place": "Colonaire", "distance_category": "To Windward", "regular_ec": 137.00, "regular_us": 51.00, "after_hours_ec": 170.00, "after_hours_us": 64.00},
      {"place": "Byera", "distance_category": "To Windward", "regular_ec": 150.00, "regular_us": 56.00, "after_hours_ec": 187.00, "after_hours_us": 70.00},
      {"place": "Park Hill", "distance_category": "To Windward", "regular_ec": 150.00, "regular_us": 56.00, "after_hours_ec": 187.00, "after_hours_us": 70.00},
      {"place": "South Rivers", "distance_category": "To Windward", "regular_ec": 150.00, "regular_us": 56.00, "after_hours_ec": 187.00, "after_hours_us": 70.00},
      {"place": "Georgetown (Bay Road)", "distance_category": "To Windward", "regular_ec": 163.00, "regular_us": 61.00, "after_hours_ec": 203.00, "after_hours_us": 77.00},
      {"place": "Orange Hill", "distance_category": "To Windward", "regular_ec": 182.00, "regular_us": 68.00, "after_hours_ec": 228.00, "after_hours_us": 56.00}, // Note: after_hours_us seems low here, data error? Using as is.
      {"place": "Overland", "distance_category": "To Windward", "regular_ec": 182.00, "regular_us": 68.00, "after_hours_ec": 228.00, "after_hours_us": 56.00}, // Note: after_hours_us seems low here, data error? Using as is.
      {"place": "Sandy Bay", "distance_category": "To Windward", "regular_ec": 208.00, "regular_us": 78.00, "after_hours_ec": 260.00, "after_hours_us": 98.00},
      {"place": "Owia", "distance_category": "To Windward", "regular_ec": 228.00, "regular_us": 86.00, "after_hours_ec": 285.00, "after_hours_us": 107.00},
      {"place": "Fancy", "distance_category": "To Windward", "regular_ec": 247.00, "regular_us": 92.00, "after_hours_ec": 309.00, "after_hours_us": 116.00},
      {"place": "Lowmans Lwd to Ash place", "distance_category": "To Leeward", "regular_ec": 26.00, "regular_us": 9.00, "after_hours_ec": 33.00, "after_hours_us": 12.00},
      {"place": "After Ash’s to Campden Park", "distance_category": "To Leeward", "regular_ec": 33.00, "regular_us": 12.00, "after_hours_ec": 40.00, "after_hours_us": 16.00},
      {"place": "Campden Park (from Junction)", "distance_category": "To Leeward", "regular_ec": 39.00, "regular_us": 14.00, "after_hours_ec": 49.00, "after_hours_us": 18.00},
      {"place": "Questelles (lower & upper)", "distance_category": "To Leeward", "regular_ec": 39.00, "regular_us": 14.00, "after_hours_ec": 49.00, "after_hours_us": 18.00},
      {"place": "Clare Valley", "distance_category": "To Leeward", "regular_ec": 46.00, "regular_us": 17.00, "after_hours_ec": 57.00, "after_hours_us": 21.00},
      {"place": "Chauncey", "distance_category": "To Leeward", "regular_ec": 46.00, "regular_us": 17.00, "after_hours_ec": 57.00, "after_hours_us": 21.00},
      {"place": "Rillian Hill", "distance_category": "To Leeward", "regular_ec": 52.00, "regular_us": 20.00, "after_hours_ec": 65.00, "after_hours_us": 25.00},
      {"place": "Penniston", "distance_category": "To Leeward", "regular_ec": 59.00, "regular_us": 22.00, "after_hours_ec": 73.00, "after_hours_us": 27.00},
      {"place": "Buccament", "distance_category": "To Leeward", "regular_ec": 59.00, "regular_us": 22.00, "after_hours_ec": 73.00, "after_hours_us": 27.00},
      {"place": "Buccama Resort", "distance_category": "To Leeward", "regular_ec": 65.00, "regular_us": 25.00, "after_hours_ec": 82.00, "after_hours_us": 30.00},
      {"place": "Emerald Valley Casino", "distance_category": "To Leeward", "regular_ec": 65.00, "regular_us": 25.00, "after_hours_ec": 82.00, "after_hours_us": 30.00},
      {"place": "Vermont", "distance_category": "To Leeward", "regular_ec": 72.00, "regular_us": 27.00, "after_hours_ec": 90.00, "after_hours_us": 34.00},
      {"place": "Above the Community Center", "distance_category": "To Leeward", "regular_ec": 78.00, "regular_us": 29.00, "after_hours_ec": 98.00, "after_hours_us": 36.00},
      {"place": "Layou", "distance_category": "To Leeward", "regular_ec": 72.00, "regular_us": 27.00, "after_hours_ec": 90.00, "after_hours_us": 34.00},
      {"place": "Mt. Wynne", "distance_category": "To Leeward", "regular_ec": 78.00, "regular_us": 28.00, "after_hours_ec": 98.00, "after_hours_us": 36.00},
      {"place": "Barrouallie", "distance_category": "To Leeward", "regular_ec": 91.00, "regular_us": 34.00, "after_hours_ec": 114.00, "after_hours_us": 43.00},
      {"place": "Keartons", "distance_category": "To Leeward", "regular_ec": 91.00, "regular_us": 34.00, "after_hours_ec": 114.00, "after_hours_us": 43.00},
      {"place": "Belle Isle Hill", "distance_category": "To Leeward", "regular_ec": 104.00, "regular_us": 39.00, "after_hours_ec": 130.00, "after_hours_us": 48.00},
      {"place": "Spring Village", "distance_category": "To Leeward", "regular_ec": 117.00, "regular_us": 44.00, "after_hours_ec": 147.00, "after_hours_us": 55.00},
      {"place": "Cumberland", "distance_category": "To Leeward", "regular_ec": 117.00, "regular_us": 44.00, "after_hours_ec": 147.00, "after_hours_us": 55.00},
      {"place": "Coulls Hill", "distance_category": "To Leeward", "regular_ec": 143.00, "regular_us": 53.00, "after_hours_ec": 179.00, "after_hours_us": 66.00},
      {"place": "Troumaca", "distance_category": "To Leeward", "regular_ec": 169.00, "regular_us": 64.00, "after_hours_ec": 212.00, "after_hours_us": 79.00},
      {"place": "Rose Bank", "distance_category": "To Leeward", "regular_ec": 169.00, "regular_us": 64.00, "after_hours_ec": 212.00, "after_hours_us": 79.00},
      {"place": "Rose Hall", "distance_category": "To Leeward", "regular_ec": 189.00, "regular_us": 70.00, "after_hours_ec": 235.00, "after_hours_us": 88.00},
      {"place": "Petit Bordel", "distance_category": "To Leeward", "regular_ec": 198.00, "regular_us": 73.00, "after_hours_ec": 244.00, "after_hours_us": 91.00},
      {"place": "Chateaubelair", "distance_category": "To Leeward", "regular_ec": 208.00, "regular_us": 78.00, "after_hours_ec": 260.00, "after_hours_us": 98.00},
      {"place": "Richmond", "distance_category": "To Leeward", "regular_ec": 245.00, "regular_us": 87.00, "after_hours_ec": 293.00, "after_hours_us": 109.00}
    ]
  },
  {
    "category": "From Cruise Ship Berth to Places and for Tours around Kingstown Taxi Fares",
    "fares": [
      {"place": "Botanical Gardens", "passengers": "1 to 4", "regular_one_way_ec": 17.00, "regular_one_way_us": 7.00, "regular_return_ec": 34.00, "regular_return_us": 14.00, "after_hours_one_way_ec": 21.00, "after_hours_one_way_us": 8.00},
      {"place": "Botanical Gardens", "passengers": "5 to 10", "regular_one_way_ec": 10.00, "regular_one_way_us": 4.00, "regular_return_ec": 21.00, "regular_return_us": 8.00, "after_hours_one_way_ec": 13.00, "after_hours_one_way_us": 5.00},
      {"place": "Fort Charlotte", "passengers": "1 to 4", "regular_one_way_ec": 69.00, "regular_one_way_us": 26.00, "regular_return_ec": 138.00, "regular_return_us": 52.00, "after_hours_one_way_ec": 86.00, "after_hours_one_way_us": 33.00},
      {"place": "Fort Charlotte", "passengers": "5 to 10", "regular_one_way_ec": 17.00, "regular_one_way_us": 7.00, "regular_return_ec": 34.00, "regular_return_us": 14.00, "after_hours_one_way_ec": 21.00, "after_hours_one_way_us": 8.00},
      {"place": "Villa Beach Area", "passengers": "1 to 4", "regular_one_way_ec": 69.00, "regular_one_way_us": 26.00, "regular_return_ec": 138.00, "regular_return_us": 52.00, "after_hours_one_way_ec": 86.00, "after_hours_one_way_us": 33.00},
      {"place": "Villa Beach Area", "passengers": "5 to 10", "regular_one_way_ec": 17.00, "regular_one_way_us": 7.00, "regular_return_ec": 34.00, "regular_return_us": 14.00, "after_hours_one_way_ec": 21.00, "after_hours_one_way_us": 8.00},
      {"place": "Questelles Beach", "passengers": "1 to 4", "regular_one_way_ec": 87.00, "regular_one_way_us": 33.00, "regular_return_ec": 174.00, "regular_return_us": 66.00, "after_hours_one_way_ec": 109.00, "after_hours_one_way_us": 41.00},
      {"place": "Questelles Beach", "passengers": "5 to 10", "regular_one_way_ec": 21.00, "regular_one_way_us": 8.00, "regular_return_ec": 42.00, "regular_return_us": 16.00, "after_hours_one_way_ec": 26.00, "after_hours_one_way_us": 10.00},
      {"place": "Vermont Nature Trail", "passengers": "1 to 4", "regular_one_way_ec": 208.00, "regular_one_way_us": 78.00, "regular_return_ec": 416.00, "regular_return_us": 156.00, "after_hours_one_way_ec": 260.00, "after_hours_one_way_us": 98.00},
      {"place": "Vermont Nature Trail", "passengers": "5 to 10", "regular_one_way_ec": 43.00, "regular_one_way_us": 16.00, "regular_return_ec": 86.00, "regular_return_us": 33.00, "after_hours_one_way_ec": 54.00, "after_hours_one_way_us": 20.00},
      {"place": "Wallilabou", "passengers": "1 to 4", "regular_one_way_ec": 156.00, "regular_one_way_us": 59.00, "regular_return_ec": 312.00, "regular_return_us": 118.00, "after_hours_one_way_ec": 195.00, "after_hours_one_way_us": 73.00},
      {"place": "Wallilabou", "passengers": "5 to 10", "regular_one_way_ec": 43.00, "regular_one_way_us": 16.00, "regular_return_ec": 86.00, "regular_return_us": 32.00, "after_hours_one_way_ec": 54.00, "after_hours_one_way_us": 20.00},
      {"place": "Wallilabou", "passengers": "Over 10", "regular_one_way_ec": 34.00, "regular_one_way_us": 13.00, "regular_return_ec": 68.00, "regular_return_us": 26.00, "after_hours_one_way_ec": 42.00, "after_hours_one_way_us": 16.00},
      {"place": "Dark View Falls", "passengers": "1 to 4", "regular_one_way_ec": 277.00, "regular_one_way_us": 104.00, "regular_return_ec": 554.00, "regular_return_us": 208.00, "after_hours_one_way_ec": 346.00, "after_hours_one_way_us": 130.00},
      {"place": "Dark View Falls", "passengers": "5 to 10", "regular_one_way_ec": 61.00, "regular_one_way_us": 23.00, "regular_return_ec": 122.00, "regular_return_us": 46.00, "after_hours_one_way_ec": 76.00, "after_hours_one_way_us": 29.00},
      {"place": "Dark View Falls", "passengers": "Over 10", "regular_one_way_ec": 52.00, "regular_one_way_us": 20.00, "regular_return_ec": 104.00, "regular_return_us": 40.00, "after_hours_one_way_ec": 65.00, "after_hours_one_way_us": 24.00},
      {"place": "Trinity Falls and Richmond, La Soufriere", "passengers": "1 to 4", "regular_one_way_ec": 347.00, "regular_one_way_us": 130.00, "regular_return_ec": 694.00, "regular_return_us": 260.00, "after_hours_one_way_ec": 434.00, "after_hours_one_way_us": 163.00},
      {"place": "Trinity Falls and Richmond, La Soufriere", "passengers": "5 to 10", "regular_one_way_ec": 69.00, "regular_one_way_us": 26.00, "regular_return_ec": 138.00, "regular_return_us": 52.00, "after_hours_one_way_ec": 86.00, "after_hours_one_way_us": 33.00},
      {"place": "Trinity Falls and Richmond, La Soufriere", "passengers": "Over 10", "regular_one_way_ec": 61.00, "regular_one_way_us": 23.00, "regular_return_ec": 122.00, "regular_return_us": 46.00, "after_hours_one_way_ec": 76.00, "after_hours_one_way_us": 29.00},
      {"place": "Owia Salt Pond", "passengers": "1 to 4", "regular_one_way_ec": 416.00, "regular_one_way_us": 156.00, "regular_return_ec": 832.00, "regular_return_us": 312.00, "after_hours_one_way_ec": 520.00, "after_hours_one_way_us": 195.00},
      {"place": "Owia Salt Pond", "passengers": "5 to 10", "regular_one_way_ec": 78.00, "regular_one_way_us": 30.00, "regular_return_ec": 156.00, "regular_return_us": 60.00, "after_hours_one_way_ec": 98.00, "after_hours_one_way_us": 37.00},
      {"place": "Owia Salt Pond", "passengers": "Over 10", "regular_one_way_ec": 70.00, "regular_one_way_us": 26.00, "regular_return_ec": 140.00, "regular_return_us": 52.00, "after_hours_one_way_ec": 86.00, "after_hours_one_way_us": 33.00},
      {"place": "Rabacca Bridge", "passengers": "1 to 4", "regular_one_way_ec": 277.00, "regular_one_way_us": 104.00, "regular_return_ec": 554.00, "regular_return_us": 208.00, "after_hours_one_way_ec": 346.00, "after_hours_one_way_us": 130.00},
      {"place": "Rabacca Bridge", "passengers": "5 to 10", "regular_one_way_ec": 61.00, "regular_one_way_us": 23.00, "regular_return_ec": 122.00, "regular_return_us": 46.00, "after_hours_one_way_ec": 76.00, "after_hours_one_way_us": 29.00},
      {"place": "Rabacca Bridge", "passengers": "Over 10", "regular_one_way_ec": 52.00, "regular_one_way_us": 20.00, "regular_return_ec": 104.00, "regular_return_us": 40.00, "after_hours_one_way_ec": 65.00, "after_hours_one_way_us": 24.00},
      {"place": "Black Point Tunnel", "passengers": "1 to 4", "regular_one_way_ec": 260.00, "regular_one_way_us": 98.00, "regular_return_ec": 520.00, "regular_return_us": 196.00, "after_hours_one_way_ec": 325.00, "after_hours_one_way_us": 122.00},
      {"place": "Black Point Tunnel", "passengers": "5 to 10", "regular_one_way_ec": 52.00, "regular_one_way_us": 20.00, "regular_return_ec": 104.00, "regular_return_us": 40.00, "after_hours_one_way_ec": 65.00, "after_hours_one_way_us": 24.00},
      {"place": "Black Point Tunnel", "passengers": "Over 10", "regular_one_way_ec": 43.00, "regular_one_way_us": 16.00, "regular_return_ec": 86.00, "regular_return_us": 32.00, "after_hours_one_way_ec": 53.00, "after_hours_one_way_us": 20.00},
      {"place": "Argyle", "passengers": "1 to 4", "regular_one_way_ec": 156.00, "regular_one_way_us": 59.00, "regular_return_ec": 312.00, "regular_return_us": 118.00, "after_hours_one_way_ec": 195.00, "after_hours_one_way_us": 73.00},
      {"place": "Argyle", "passengers": "5 to 10", "regular_one_way_ec": 43.00, "regular_one_way_us": 16.00, "regular_return_ec": 86.00, "regular_return_us": 32.00, "after_hours_one_way_ec": 54.00, "after_hours_one_way_us": 20.00},
      {"place": "Argyle", "passengers": "Over 10", "regular_one_way_ec": 34.00, "regular_one_way_us": 13.00, "regular_return_ec": 68.00, "regular_return_us": 26.00, "after_hours_one_way_ec": 42.00, "after_hours_one_way_us": 16.00},
      {"place": "Montreal Gardens", "passengers": "1 to 4", "regular_one_way_ec": 242.00, "regular_one_way_us": 91.00, "regular_return_ec": 484.00, "regular_return_us": 182.00, "after_hours_one_way_ec": 306.00, "after_hours_one_way_us": 114.00},
      {"place": "Montreal Gardens", "passengers": "5 to 10", "regular_one_way_ec": 52.00, "regular_one_way_us": 20.00, "regular_return_ec": 104.00, "regular_return_us": 40.00, "after_hours_one_way_ec": 65.00, "after_hours_one_way_us": 24.00},
      {"place": "Montreal Gardens", "passengers": "Over 10", "regular_one_way_ec": 43.00, "regular_one_way_us": 16.00, "regular_return_ec": 86.00, "regular_return_us": 32.00, "after_hours_one_way_ec": 54.00, "after_hours_one_way_us": 20.00}
    ]
  },
  {
    "category": "Tours around Kingstown (Minimum of two (2) hours)",
    "fares": [
      {"passengers": "1 to 4", "regular_return_ec": 104.00, "regular_return_us": 39.00, "after_hours_return_ec": 130.00, "after_hours_return_us": 49.00},
      {"passengers": "5 to 10", "regular_return_ec": 27.00, "regular_return_us": 10.00, "after_hours_return_ec": 34.00, "after_hours_return_us": 13.00},
      {"passengers": "Over 10", "regular_return_ec": 23.00, "regular_return_us": 9.00, "after_hours_return_ec": 29.00, "after_hours_return_us": 11.00}
    ]
  }
];

export const EC_TO_US_RATE = 2.70; // Standard exchange rate for XCD to USD
